### ISSUE TITLE
Miner identifier

### ISSUE THREAD

**Issue by bauen1** [bauen1/KristMiningPool#1]
Have you any ideas what should be used as an id for each miner?

**Comment by Luca0208** [comment]
You could make the user enter one(If you mean multiple miners per users) if you process miners on the server increasing ID's would be better.

**Comment by bauen1** [comment]
So you mean i let the miner call a function on the pool with the address he would like to receive his money and he is given a id wich he then adds to all further api calls?
(More advanced way could add an gui)

**Comment by Luca0208** [comment]
Idk what exactly you mean with ID, I would let the user be able to define an ID(At least that is how it goes no most real BTC pools), but if you need a unique ID to handle it on the server you should give them increasing numbers.

**Comment by bauen1** [comment]
I'm just gonna use the miners payout address for now
